### ISSUE TITLE
Standarize Data Format

### ISSUE THREAD

**Issue by TK-21st** [fruitflybrain/neu3d#21]
Neu3D currently handles loading data of a few formats, here we standardize the input data formats.

## Input format
MorphologyData sent for multiple objects should be a dictionary with the rid of Morphology data as the key,
and each value is a dictionary with the following fields:
- class: the type of data, e.g., 'Neuron', 'Synapse', 'Neuropil', etc.
- orid: the rid of the parent node,
- morph_type: the type of data
and fields according to the morph_type.

## MeshDict Object (output items in MeshDict)
- ffbo_json: {[rid:string]: data_to_be_loaded}
- type: 'morphology_json' | 'gltf' | string
- highlight: boolean
- visibility: boolean
- background: boolean
- color: THREE.Color | string (RGB hex)
- label: string
- colormap: string;
- colororder: 'random' | 'order;
- showAfterLoadAll: boolean;
- reset: boolean 

### if loading from file
- filename: string
- filetype: 'json' | 'swc' | 'syn' | 'gltf'

### if loading from Obj
- dataStr: string

### Morphology Transformations
The following attributes will be applied to all except gltf files.

- radius_scale = 1.
- x_scale = 1.
- y_scale = 1.
- z_scale = 1.
- x_shift = 0.
- y_shift = 0.
- z_shift = 0.
- xy_rot = 0.
- yz_rot = 0.
- xz_rot = 0.

### Attributes added by `_registerObject`
- rid: string
- object: RenderObj
- pinned = false
- position: THREE.Vector3
- opacity: float

## SWC (`loadSWCCallBack`)
Each row of the `swcString` is assumed to be a length-7 array with each item corresponding to the following entries

| sample | type | x | y | z| radius |parent|
| ------- | -----|---|--|--|-------|------|
| int | int | float | float | float | float | int|

### type
- 0: undefined
- 1: soma
- 2: axon
- 3: (basal) dendrite
- 4: apical dendrite
- 5: custom
- 6: custom

`parent = -1` indicates root

## Mesh (`loadMeshCallBack`)
- vertices: Array<float>
- faces: Array<int>

## MorphJSON (`loadMorphJSONCallBack`)
MorphJSON is assumed to be a json of 7 fields (as below) where each field is an array of corresponding items.

| sample | identifier | x | y | z| r |parent|
| ------- | -----|---|--|--|-------|------|
| int | int | float | float | float | float | int|

identifiers used for Neurons:

- 0: undefined
- 1: soma

Synapses need to take the special format to start listing all presynaptic sites with parent -1 and followed by postsynaptic sites using sample of its presynaptic sites as parent, e.g.
| sample | identifier | x | y | z| r |parent|
| ------- | -----|---|--|--|-------|------|
| 1 | 7 | float | float | float | float | -1|
| 2 | 7 | float | float | float | float | -1|
| 3 | 7 | float | float | float | float | -1|
| 4 | 8 | float | float | float | float | 1|
| 5 | 8 | float | float | float | float | 2|
| 6 | 8 | float | float | float | float | 3|

## GLTF  (`loadGltfCallBack`)

- dataStr

**Comment by TK-21st** [comment]
@yiyin, related to my comment in #32, can you add in comments/edits to this issue?

**Comment by yiyin** [comment]
made some edits above

**Comment by TK-21st** [comment]
> made some edits above

Great! Thanks! Will add this to a schema checker to object loader.

**Comment by yiyin** [comment]
## Schema for MorphologyData (as of [Neuroarch version 0.3.2](https://github.com/fruitflybrain/neuroarch/tree/0.3.2))

### 'swc'
- x: list of double
- y: list of double
- z: list of double
- r: list of double
- parent: list of int
- sample: list of int
- identifier: list of int
- confidence: list of double (optional, for synapse only)

### 'mesh':
- faces: list of int, the first vertex is indexed as 0
- vertices: list of double, the length should be 3 times the number of vertices , e.g., `[v[0].x, v[0].y, v[0].z, v[1].x, v[1].y, v[1].z, ...]`

### 'obj'
not currently defined

**Comment by TK-21st** [comment]
Thanks @yiyin!
Closed by 1a01f9450c0b46a6e2bf4fcd8b62dd97e9033520
